# GENERAL CONFIGURATION #
#version format
version: '1.0.{build}'

#branches to build
branches:
  only:
    - master

#don't build on tags
skip_tags: true

# ENVIRONMENT CONFIGURATION #
#build image
image:
  - Visual Studio 2017

init:
  - set QTDIR=C:\Qt\5.11.1\msvc2017_64
  - set PATH=%QTDIR%\bin;%PATH%
  - set ORIGPATH=%PATH%
  
clone_folder: c:\%PROJECT_NAME%

shallow_clone: true

clone_depth: 5   

environment:
  PROJECT_NAME: chrome-password-reader

#the build fail once the job fails
matrix:
  fast_finish: true

# BUILD CONFIGURATION #
before_build:
    - cd c:\%PROJECT_NAME%
    - md build

build_script:
  - cd build
  - cmake .. -G "Visual Studio 15 2017 Win64"
  - cmake --build . --config Release

after_build:
  - cd C:\%PROJECT_NAME%\build\Release\
  - windeployqt.exe --no-opengl-sw --no-translations --no-system-d3d-compiler -no-angle ./chrome-password-reader.exe 
  - 7z a %PROJECT_NAME%-win-x64.zip ./*
  - move %PROJECT_NAME%-win-x64.zip C:\%PROJECT_NAME%\%PROJECT_NAME%-win-x64.zip

# TEST CONFIGURATION #
test: off

# ARTIFACTS AND DEPLOYMENT CONFIGURATION #
artifacts:
  - path: '%PROJECT_NAME%-win-x64.zip'
    name: artifacts
    
deploy:
  release: v$(appveyor_build_version)
  description: Software for Windows
  tag: v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: PTmCCvHOYwSne/qGWheaYLb15X89BkUzh/hi8Zem+P3oGsLn6pAMuY21IbpYk83I
  artifact: '%PROJECT_NAME%-win-x64.zip'